FROM postgres:latest
MAINTAINER thibault.theologien@insa-rouen.fr
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="evasion"
ENV POSTGRES_DB="asijmennuie"
VOLUME /docker-entrypoint-initdb.d/
WORKDIR /docker-entrypoint-initdb.d/
